# User programs - only installation and Nix integration
# All config files are handled by symlinks.nix
{ pkgs, inputs, endcord, ... }:
{
  # Shell
  programs.fzf = {
    enable = true;
    enableFishIntegration = true;
  };
  programs.zoxide = {
    enable = true;
    enableFishIntegration = true;
  };
  # Prompt — config at ~/.config/starship.toml is generated by the theme
  # system and symlinked from ~/dotfiles/starship/ via symlinks.nix.
  programs.starship = {
    enable = true;
    enableFishIntegration = true;
  };

  # Editor — neovim installed directly rather than via programs.neovim, since HM's
  # module generates its own init.lua which conflicts with the dotfile-based config
  # symlinked through symlinks.nix.
  home.packages = (with pkgs; [
    neovim-unwrapped
    # LSP/formatter tooling expected on PATH by the nvim config
    prettier
    black
    stylua
    eslint
    xclip
    # mpv — used by ~/.config/endcord/media-viewer.sh to play gif-as-mp4
    # attachments (Discord converts giphy gifv to mp4 server-side).
    mpv
  ]) ++ [
    # Helium browser — wrapped via flake (not in nixpkgs). Ships its own
    # .desktop entry and icon, so no xdg.desktopEntries needed.
    inputs.helium-nix.packages.${pkgs.system}.default
    # endcord — Discord TUI 1.4.2, built from source. See pkgs/endcord/default.nix.
    endcord
  ];
  home.sessionVariables.EDITOR = "nvim";
  programs.fish.shellAliases = {
    vi = "nvim";
    vim = "nvim";
  };

  # Git
  programs.git.enable = true;
  programs.gh = {
    enable = true;
    settings = {
      git_protocol = "ssh";
      editor = "nvim";
    };
  };
  programs.lazygit.enable = true;

  # Git worktree management
  programs.worktrunk = {
    enable = true;
    enableFishIntegration = true;
  };
}
