# User programs - only installation and Nix integration
# All config files are handled by symlinks.nix
{ pkgs, inputs, endcord, ... }:
let
  palette-daemon = inputs.palette-daemon.packages.${pkgs.system}.default;
in
{
  # Shell
  programs.fzf = {
    enable = true;
    enableFishIntegration = true;
  };
  programs.zoxide = {
    enable = true;
    enableFishIntegration = true;
  };
  # Prompt — config at ~/.config/starship.toml is generated by the theme
  # system and symlinked from ~/dotfiles/starship/ via symlinks.nix.
  programs.starship = {
    enable = true;
    enableFishIntegration = true;
  };

  # Editor — neovim installed directly rather than via programs.neovim, since HM's
  # module generates its own init.lua which conflicts with the dotfile-based config
  # symlinked through symlinks.nix.
  home.packages = (with pkgs; [
    neovim-unwrapped
    # LSP/formatter tooling expected on PATH by the nvim config
    prettier
    black
    stylua
    eslint
    xclip
    # mpv — used by ~/.config/endcord/media-viewer.sh to play gif-as-mp4
    # attachments (Discord converts giphy gifv to mp4 server-side).
    mpv
  ]) ++ [
    # Helium browser — locally pinned to 0.12.2.1 (pre-release) until the
    # helium-nix flake auto-bumper picks it up. See pkgs/helium/default.nix
    # for context and revert instructions. Ships its own .desktop and icon,
    # so no xdg.desktopEntries needed.
    (pkgs.callPackage ../../pkgs/helium {})
    # endcord — Discord TUI 1.4.2, built from source. See pkgs/endcord/default.nix.
    endcord
    # palette-daemon — WebKit command-palette overlay, replacing the
    # per-tab iframe prewarm. Service unit defined below.
    palette-daemon
  ];

  # palette-daemon as a user systemd service, mirroring mako's pattern
  # (PartOf graphical-session.target, ExecCondition gate on
  # WAYLAND_DISPLAY). The chromium-palette popup bundle still lives in
  # ~/personal/chromium-palette/dist; PALETTE_POPUP_DIST pins it.
  systemd.user.services.palette-daemon = {
    Unit = {
      Description = "Palette Daemon (WebKit command-palette overlay)";
      PartOf = [ "graphical-session.target" ];
      After = [ "graphical-session.target" ];
    };
    Service = {
      Type = "simple";
      ExecCondition = "/bin/sh -c '[ -n \"$WAYLAND_DISPLAY\" ]'";
      ExecStart = "${palette-daemon}/bin/palette-daemon";
      Environment = [
        "PALETTE_POPUP_DIST=%h/personal/chromium-palette/dist"
        "RUST_LOG=palette_daemon=info"
      ];
      Restart = "on-failure";
      RestartSec = 2;
    };
    Install.WantedBy = [ "graphical-session.target" ];
  };
  home.sessionVariables.EDITOR = "nvim";
  programs.fish.shellAliases = {
    vi = "nvim";
    vim = "nvim";
  };

  # Git
  programs.git.enable = true;
  # Default changed at HM 25.05 ("openpgp" → null). Pin explicitly so the
  # warning silences and behavior stays consistent across stateVersion bumps.
  programs.git.signing.format = "openpgp";
  programs.gh = {
    enable = true;
    settings = {
      git_protocol = "ssh";
      editor = "nvim";
    };
  };
  programs.lazygit.enable = true;

  # Git worktree management
  programs.worktrunk = {
    enable = true;
    enableFishIntegration = true;
  };
}
