# User programs - only installation and Nix integration
# All config files are handled by symlinks.nix
{ pkgs, inputs, nvimLocal, nvimBaked, ... }:
let
  palette-daemon = inputs.palette-daemon.packages.${pkgs.system}.default;
  # Native QML chat clients. Each input exposes the daemon (`slqs`/`dsqrd`) and
  # the launch wrapper (`slqs-client`/`dsqrd-client`, which ensures the daemon
  # then opens the Quickshell UI from the store). The niri launchers + the
  # startup daemon line in config.kdl reference these.
  slqsDaemon = inputs.slqs.packages.${pkgs.system}.slqs;
  slqsClient = inputs.slqs.packages.${pkgs.system}.slqs-client;
  dsqrdDaemon = inputs.dsqrd.packages.${pkgs.system}.dsqrd;
  dsqrdClient = inputs.dsqrd.packages.${pkgs.system}.dsqrd-client;
  # nvim — the converged config (0.12, lz.n, native LSP), with the desktop
  # "full" profile (extras like pyright gated behind NVIM_PROFILE=full and
  # layered onto PATH). Lua lives in ~/dotfiles/nvim and is read live from
  # ~/.config/nvim, so lua edits apply with no rebuild. Old lazy config is
  # archived under ~/dotfiles/nvim-lazy.
  nvim = pkgs.writeShellScriptBin "nvim" ''
    export NVIM_PROFILE=full
    export PATH=${pkgs.lib.makeBinPath [ pkgs.pyright ]}:$PATH
    exec ${nvimLocal}/bin/nvim "$@"
  '';
  # nvim-next — baked-from-github variant (what sandboxes get). Sources the
  # config from the dotfiles flake input, so it lags local edits until they're
  # pushed + the input bumped. Kept as a fallback and a sandbox-preview.
  nvim-next = pkgs.writeShellScriptBin "nvim-next" ''
    export NVIM_PROFILE=full
    export PATH=${pkgs.lib.makeBinPath [ pkgs.pyright ]}:$PATH
    exec ${nvimBaked}/bin/nvim "$@"
  '';
in
{
  # Shell
  programs.fzf = {
    enable = true;
    enableFishIntegration = true;
  };
  programs.zoxide = {
    enable = true;
    enableFishIntegration = true;
  };
  # Prompt — config at ~/.config/starship.toml is generated by the theme
  # system and symlinked from ~/dotfiles/starship/ via symlinks.nix.
  programs.starship = {
    enable = true;
    enableFishIntegration = true;
  };

  # Editor — neovim installed directly rather than via programs.neovim, since HM's
  # module generates its own init.lua which conflicts with the dotfile-based config
  # symlinked through symlinks.nix.
  home.packages = [ nvim nvim-next ] ++ (with pkgs; [
    # LSP/formatter tooling expected on PATH by the nvim config
    prettier
    black
    stylua
    eslint
    xclip
    # mpv — used by the media-viewer.sh (in ~/.config/endcord/) that the native
    # QML chat clients (slqs/dsqrd) call to play gif-as-mp4 attachments.
    mpv
  ]) ++ [
    # Helium browser via the upstream auto-bumped flake. Ships its own
    # .desktop and icon, so no xdg.desktopEntries needed.
    inputs.helium-nix.packages.${pkgs.system}.default
    # palette-daemon — WebKit command-palette overlay, replacing the
    # per-tab iframe prewarm. Service unit defined below.
    palette-daemon
    # Native QML Slack/Discord clients (daemon + launch wrapper each).
    slqsDaemon
    slqsClient
    dsqrdDaemon
    dsqrdClient
  ];

  # wpm-daemon — burst-based WPM counter. Reads /dev/input/event* (needs
  # `input` group, added in common/default.nix) and writes the current
  # value to ~/.local/state/wpm where the QS Wpm widget picks it up.
  # Local-source build for now; lives at ~/personal/wpm-daemon.
  systemd.user.services.wpm-daemon = {
    Unit = {
      Description = "WPM daemon — keystroke rate counter for the QS bar";
      PartOf = [ "graphical-session.target" ];
      After = [ "graphical-session.target" ];
    };
    Service = {
      Type = "simple";
      ExecStart = "%h/personal/wpm-daemon/target/release/wpm-daemon";
      Restart = "on-failure";
      RestartSec = 2;
    };
    Install.WantedBy = [ "graphical-session.target" ];
  };

  # palette-daemon as a user systemd service, mirroring mako's pattern
  # (PartOf graphical-session.target, ExecCondition gate on
  # WAYLAND_DISPLAY). The chromium-palette popup bundle still lives in
  # ~/personal/chromium-palette/dist; PALETTE_POPUP_DIST pins it.
  systemd.user.services.palette-daemon = {
    Unit = {
      Description = "Palette Daemon (WebKit command-palette overlay)";
      PartOf = [ "graphical-session.target" ];
      After = [ "graphical-session.target" ];
    };
    Service = {
      Type = "simple";
      ExecCondition = "/bin/sh -c '[ -n \"$WAYLAND_DISPLAY\" ]'";
      ExecStart = "${palette-daemon}/bin/palette-daemon";
      Environment = [
        "PALETTE_POPUP_DIST=%h/personal/chromium-palette/dist"
        "RUST_LOG=palette_daemon=info"
        # Force GTK4's OpenGL renderer instead of the default Vulkan one.
        # The Vulkan swapchain doesn't recreate on output reconfiguration
        # (VK_SUBOPTIMAL_KHR in journal logs), which bilinear-stretches the
        # webview to the new surface dimensions — the "palette becomes
        # fuzzy after unplugging external monitors" symptom.
        "GSK_RENDERER=ngl"
      ];
      Restart = "on-failure";
      RestartSec = 2;
    };
    Install.WantedBy = [ "graphical-session.target" ];
  };
  home.sessionVariables.EDITOR = "nvim";
  programs.fish.shellAliases = {
    vi = "nvim";
    vim = "nvim";
  };

  # Git
  programs.git.enable = true;
  # Default changed at HM 25.05 ("openpgp" → null). Pin explicitly so the
  # warning silences and behavior stays consistent across stateVersion bumps.
  programs.git.signing.format = "openpgp";
  programs.gh = {
    enable = true;
    settings = {
      git_protocol = "ssh";
      editor = "nvim";
    };
  };
  programs.lazygit.enable = true;

  # Git worktree management
  programs.worktrunk = {
    enable = true;
    enableFishIntegration = true;
  };
}
