local api, fn = vim.api, vim.fn
local cockpit = require("cockpit")
local root = fn.tempname()
fn.mkdir(root, "p")
local function git(dir, ...)
  local args = { "git", "-C", dir }
  vim.list_extend(args, { ... })
  local result = fn.systemlist(args)
  assert(vim.v.shell_error == 0, table.concat(result, "\n"))
  return result
end
local function fixture(name)
  local dir = root .. "/" .. name
  fn.mkdir(dir .. "/.plans", "p")
  git(dir, "init", "-b", "main")
  fn.writefile({ "first", "second", "third" }, dir .. "/code.txt")
  git(dir, "add", "code.txt")
  git(dir, "-c", "user.name=Test", "-c", "user.email=test@example.com", "commit", "-m", "base")
  git(dir, "checkout", "-b", "ticket")
  fn.writefile({ "first", "changed", "third" }, dir .. "/code.txt")
  git(dir, "add", "code.txt")
  git(dir, "-c", "user.name=Test", "-c", "user.email=test@example.com", "commit", "-m", "implementation")
  fn.writefile({ "# " .. name, "", "Status: finalized" }, dir .. "/.plans/" .. name .. ".md")
  return dir
end
local a, b = fixture("WORKSPACE-A"), fixture("WORKSPACE-B")
local function view(scope, id, dir, which, latest)
  cockpit.workspace(scope, id, dir, fn.fnamemodify(dir, ":t"), which, latest or "")
end
local checks = 0
local function check(test, message)
  assert(test, message)
  checks = checks + 1
end
view("work", "ticket", a, "code", a .. "/code.txt")
check(fn.getcwd() == a, "selection binds cwd")
api.nvim_win_set_cursor(0, { 2, 3 })
api.nvim_buf_set_lines(0, 1, 2, false, { "unsaved change" })
view("work", "ticket", a, "cycle")
check(api.nvim_buf_get_name(0) == a .. "/.plans/WORKSPACE-A.md", "code cycles to exact plan")
view("work", "ticket", a, "cycle")
check(cockpit.dashboard_snapshot().active, "plan cycles to dashboard")
check(cockpit.dashboard_snapshot().model.cwd == a, "dashboard owns ticket checkout")
view("work", "ticket", a, "cycle")
check(api.nvim_buf_get_name(0) == a .. "/code.txt", "dashboard cycles back to code")
check(api.nvim_get_current_line() == "unsaved change", "unsaved buffer survives")
check(vim.deep_equal(api.nvim_win_get_cursor(0), { 2, 3 }), "cursor survives")
view("personal", "ticket", b, "code", b .. "/code.txt")
check(api.nvim_buf_get_name(0) == b .. "/code.txt", "same session name in another scope stays isolated")
view("work", "ticket", a, "code")
check(api.nvim_get_current_line() == "unsaved change", "switch back restores selected session")
view("work", "ticket", a, "plan")
vim.cmd.cd(fn.fnameescape(b))
vim.cmd.CockpitChanges()
local picker = Snacks.picker.get()[1]
check(picker ~= nil, "Ctrl-F entry opens picker")
check(vim.wait(3000, function() return not picker.finder:running() and not picker.matcher:running() and #picker:items() > 0 end), "async diff rows arrive")
local files = picker:items()
check(vim.iter(files):any(function(item) return item.file == a .. "/code.txt" end), "committed ticket diff uses binding, not cwd or plan repo")
check(not vim.iter(files):any(function(item) return item.file == b .. "/code.txt" end), "other checkout excluded")
local missing = root .. "/MISSING"
view("work", "missing", missing, "dashboard")
check(cockpit.dashboard_snapshot().model.cwd == missing, "missing mirror dashboard never falls back")
vim.cmd.CockpitChanges()
check(#Snacks.picker.get() == 0, "missing mirror blocks diff in unrelated cwd")
check(cockpit.workspace_cwd() == nil, "missing checkout is explicit")
view("work", "ticket", a, "diff")
check(vim.wait(2000, function() return #Snacks.picker.get() == 1 end), "real diff picker opens")
check(vim.bo.filetype == "snacks_picker_input", "diff picker keeps keyboard focus")
view("work", "ticket", a, "plan")
check(#Snacks.picker.get() == 0, "switching views closes diff picker")
check(api.nvim_buf_get_name(0) == a .. "/.plans/WORKSPACE-A.md", "plan is visible after closing picker")
cockpit.workspace("personal", "no-plan", b, "", "code", b .. "/code.txt")
cockpit.workspace("personal", "no-plan", b, "", "cycle", "")
check(cockpit.dashboard_snapshot().active, "cycle skips absent plan")
view("work", "plan-writer", a, "code", a .. "/.plans/WORKSPACE-A.md")
check(#Snacks.picker.get() == 1, "latest plan edit opens diff picker, not plan as code")
fn.writefile({ "newest edit" }, a .. "/latest.txt")
view("work", "ticket", a, "", a .. "/latest.txt")
check(api.nvim_buf_get_name(0) == a .. "/latest.txt", "session switch prefers latest edit over saved code")
view("personal", "ticket", b, "")
check(cockpit.dashboard_snapshot().active and cockpit.dashboard_snapshot().model.cwd == b, "session without an edit lands on its own dashboard")
view("work", "ticket", a, "")
check(cockpit.dashboard_snapshot().active, "uncached history initially lands on selected dashboard")
cockpit.follow_remote(a, a .. "/latest.txt", false)
check(api.nvim_buf_get_name(0) == a .. "/latest.txt", "late history advances resting dashboard to latest code")
view("work", "ticket", a, "plan")
cockpit.follow_remote(a, a .. "/latest.txt", false)
check(api.nvim_buf_get_name(0) == a .. "/.plans/WORKSPACE-A.md", "late history respects explicit plan navigation")
view("work", "ticket", a, "", a .. "/deleted.txt")
check(cockpit.dashboard_snapshot().active, "unreadable latest edit falls back to selected dashboard")
local directory_changes = 0
local watch = api.nvim_create_autocmd("DirChanged", { callback = function() directory_changes = directory_changes + 1 end })
view("work", "ticket", a, "plan")
view("work", "ticket", a, "dashboard")
check(directory_changes == 0, "view switches do not retrigger checkout setup")
api.nvim_del_autocmd(watch)
print("workspace: " .. checks .. " passed")
fn.delete(root, "rf")
vim.cmd("qa!")
