#? Config file for btop v.1.4.6

color_theme = "custom"
theme_background = true
truecolor = true
vim_keys = true
rounded_corners = true
terminal_sync = true
update_ms = 2000
proc_sorting = "cpu lazy"
proc_mem_bytes = true
show_swap = true
show_disks = true
use_fstab = false
check_temp = true
show_coretemp = true
show_battery = true
show_uptime = true
